# Generated by Django 3.1.6 on 2021-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_recommendation', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата рекомендации')),
                ('patient_name', models.CharField(max_length=150, verbose_name='ФИО пациента')),
                ('patient_dob', models.CharField(max_length=100, verbose_name='Дата рождения')),
                ('diagnoses', models.CharField(max_length=500, null=True, verbose_name='Диагнозы')),
                ('recommendations', models.TextField(verbose_name='Рекомендации')),
                ('diet', models.TextField(null=True, verbose_name='Диета')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
